### ISSUE TITLE
Wakatime not installing correctly via Notepad++

### ISSUE THREAD

**Issue by Panzerbjrn** [wakatime/notepadpp-wakatime#43] opened 2021-08-21 20:15 UTC
Hi, 

I have 2 bugs/issues with Wakatime for Notepad++

1) When installing via the plugin manager, as described here, the %appdata%\Wakatime files are not installed, so Wakatime can't update.

2) Wakatime will periodically freeze Notepad++, and the only way to get control is to either kill the process, or close it from the taskbar.
This will happen seemingly at random, and can be after 5 minutes, or 2 hours, or anything in-between.

Both behaviours occur with x64 v8.1.2 and x86 v7.9.1 on Windows 10, with al the latest updates installed.

**Comment by alanhamlett** [comment] 2022-06-06 04:23
The second issue is a duplicate of #48 and fixed in v4.3.0.

Can you check if the install/update issue if also fixed in the latest release?

**Closed as completed** 2022-06-06 12:41 UTC
