### ISSUE TITLE
Notepad 6.6.8 Hangs

### ISSUE THREAD

**Issue by gacekssj4** [wakatime/notepadpp-wakatime#21] opened 2016-12-07 14:08 UTC
When I install this plugin on my N++ it hangs my editor. It's not "Program has stopped working" but I  totally cannot interact with my notepad. Can't close it. Have to shut it from task manager. Its happens everytime after 1-10 minutes.

**Comment by Pytak** [comment] 2016-12-15 07:39
Sadly, WakaTime with NPP 7.2.2 does the same.

**Comment by alanhamlett** [comment] 2019-04-10 15:53
Possible duplicate of #27.

**Closed as completed** 2019-05-01 14:07 UTC
Labels: need review
