### ISSUE TITLE
This ANSI Plugin is not compatible with your Unicode Notepadd++

### ISSUE THREAD

**Issue by darhanger** [wakatime/notepadpp-wakatime#46] opened 2021-11-13 22:03 UTC
![image](https://user-images.githubusercontent.com/22445395/141660187-e4ffff64-066b-418d-ad57-c95ab08e943e.png)

![image](https://user-images.githubusercontent.com/22445395/141660192-e6bb9a80-8fed-4a29-a8a6-d9aae6fa7974.png)

@alanhamlett

**Comment by alanhamlett** [comment] 2021-11-14 01:04
Can you try re-installing the plugin? I just released the binaries again, because I used the ones not in `\bin` folder by accident.

**Comment by alanhamlett** [comment] 2022-06-06 04:24
Can you check if the latest release works? v4.3.0

**Comment by Cyborgindustries** [comment] 2022-06-06 08:02
I just downloaded 4.3.0 and have the "This ANSI Plugin is not compatible with your Unicode Notepadd++" error

**Comment by QuentiumYT** [comment] 2022-06-06 10:21
Same here, I just rebuild the projet on my PC and it works fine
Thanks for the fix anyway! 👍

**Comment by alanhamlett** [comment] 2022-06-06 12:52
I just re-built with VS 2017, can you install from these release zips and see if it's fixed?
https://github.com/wakatime/notepadpp-wakatime/releases/tag/4.3.0

**Comment by Cyborgindustries** [comment] 2022-06-06 13:25
same issue.

**Comment by angry-master-yoda** [comment] 2022-06-06 13:37
The same with NPP 8.3.3. Plugin version 4.3.0.

**Comment by alanhamlett** [comment] 2022-06-06 14:36
I wonder what's different when you build it(working) vs when appveyor(broken) builds the release.

**Comment by QuentiumYT** [comment] 2022-06-06 18:09
Isn't it this commit: https://github.com/wakatime/notepadpp-wakatime/commit/ad3da7080023ae7a55795883e6bc3cfd2c77768b?

I built it with VS 2019 latest and TargetFrameworkVersion 4.6.1, everything worked if that helps

**Comment by alanhamlett** [comment] 2022-06-07 12:58
> Isn't it this commit: [ad3da70](https://github.com/wakatime/notepadpp-wakatime/commit/ad3da7080023ae7a55795883e6bc3cfd2c77768b)?
> 
> I built it with VS 2019 latest and TargetFrameworkVersion 4.6.1, everything worked if that helps

Without that commit it works, but with that commit it doesn't? I don't see anything in that commit that would cause unicode incompatibility.

**Comment by QuentiumYT** [comment] 2022-06-07 14:46
There was several changes to appveyor in this commit, this was just a possible hint.

**Comment by j6hg5a** [comment] 2022-08-25 15:09
Any update on this? The same issue with the latest NPP 8.4.4. Plugin version 4.3.0.

**Comment by QuentiumYT** [comment] 2022-08-25 16:03
Can confirm using the build from the releases, also since I had this issue, I built it and it works for a while now.

I know this isn't really safe for you, but here's my output of the plugin: https://quentium.fr/+Files/ghfiles/WakaTime.dll
Which should be placed on your plugin folder `C:\Program Files\Notepad++\plugins\WakaTime\WakaTime.dll` in my case

The devs might build the resource again so if you prefer their versions, I can totally agree :)

**Comment by modem7** [comment] 2022-09-12 12:50
I also noticed that 4.2.3 is the latest version available on the Notepad++ plugin admin as well.

**Comment by seowner** [comment] 2022-11-04 06:55
Is there any update on this? I still can't use 4.3.0 in Notepad++

@QuentiumYT Is there anyway you could upload your build again?

**Comment by QuentiumYT** [comment] 2022-11-04 08:09
@seowner Sure, I guess their compiled version has an issue. Btw, I think I experienced this issue only once since I use version 4.3.0.
https://quentium.fr/+Files/github/WakaTime.dll (just moved its URL)

**Comment by seowner** [comment] 2022-11-04 09:26
@QuentiumYT Thanks man greatly appreciated. I almost can't believe the devs haven't fixed this and it's been so long... But either way, I really appreciate. Hopefully this fixes the freezing issue, as without Auto Save plugin, I'd be completely screwed right now from having to force quit so many times.

**Comment by QuentiumYT** [comment] 2022-11-04 10:13
@seowner No problem :) The devs did fixes this freeze bug tho, it's just an issue with their compiled dll for the latest version (not available in npp, that's why). Hopefully the build will eventualy be fixed to have a more official version of it ^^
Tell me if you still have freezing issues anyway, and don't forget to smash some CTRL+S in addition just in case haha

**Comment by seowner** [comment] 2022-11-04 11:11
@QuentiumYT Damn, the freeze thing still happens to me even with your version. I love being able to track my stats, but being unable to ctrl+z and go back to previous edits every few hours is... quite frustrating.

**Comment by QuentiumYT** [comment] 2022-11-04 11:24
@seowner Weird thing, are you sure this is not caused by another plugin? I didn't experienced that for weeks, also if you code hours in notepad I can suggest you to change your IDE, it'll probably fit better in most cases ^^
Will check this evening if I can reproduce this bug (you can also give me more info of how you trigger it)

**Comment by seowner** [comment] 2022-11-11 09:56
@QuentiumYT It seems one way to trigger it is by applying any sort of visual style to Windows OS. Another way to potentially trigger it is by trying to open Notepad++ while it's already open. Also I have dual monitors, and Notepad++ is always on the second one, not sure if this could be related.

The absolute worst part of this is that completely destroys my Dook Bookmarks... it's unbearable and sadly it seems I'm going to have to uninstall Wakatime if the devs don't fix this issue -_-; I've re-done hundreds of bookmarks multiple times. Even saving the session doesn't work to restore them. Something about force closing Notepad++ causes the issue.

**Comment by QuentiumYT** [comment] 2022-11-11 20:25
@seowner What do you mean by "visual style to Windows OS"?
Anyway, I cannot seem to trigger any of these at all. I do also have 2 monitors and try everything I experienced previously (are you sure you have my dll version perhaps?) Also are you sure it's not another plugin now causing these freezes?
I cannot help you more, try to have only Wakatime installed, update Np++ and check if you windows doesn't have a refresh issue

**Comment by seowner** [comment] 2022-11-12 06:43
@QuentiumYT I appreciate your help, sadly, I'll have to wait until the devs figure out the issue it seems. I've also considered switching to VSCode, just don't currently have time to learn how to do macros etc in that system, I have dozens in Np++.

Anyways, thanks a lot!

**Comment by seowner** [comment] 2022-11-13 10:47
@QuentiumYT I think maybe the latest version of Notepad++ fixed the issue. I upgraded Np++ and downgraded back to 4.2.3. Haven't had the issue happen in several days thankfully.

**Closed as completed** 2022-12-05 16:55 UTC
